name: "Update pinned Nixpkgs"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Update at 12:00 every Thursday
    - cron:  '0 12 * * 4'
  workflow_dispatch:

jobs:
  update-pin:
    name: Update pinned Nixpkgs
    runs-on: ubuntu-24.04
    if: "github.repository_owner == 'NixOS'"
    steps:
      # Use a GitHub App to create the PR so that CI gets triggered
      # The App is scoped to Repository > Contents and Pull Requests: write for Nixpkgs
      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ vars.NIXPKGS_CI_APP_ID }}
          private-key: ${{ secrets.NIXPKGS_CI_APP_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Nixpkgs revision for update script
        run: |
          # pin to a commit from nixpkgs-unstable to avoid e.g. building nixf
          # from staging
          # This should not be a URL, because it would allow PRs to run arbitrary code in CI!
          rev=$(jq -r .rev ci/pinned-nixpkgs.json)
          echo "url=https://github.com/NixOS/nixpkgs/archive/$rev.tar.gz" >> "$GITHUB_ENV"

      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          extra_nix_config: sandbox = true
          nix_path: nixpkgs=${{ env.url }}

      - name: Run update script
        run: |
          # Prepare a branch
          branch_name="ci/update-pinned-nixpkgs"
          git switch --force-create "$branch_name" master
          git branch --set-upstream-to "origin/$branch_name"

          # Run script
          ci/update-pinned-nixpkgs.sh

          # Commit changes
          git commit -m "ci: Update pinned Nixpkgs"

          # Create PR
          git push --force origin "$branch_name"
          gh pr create --fill
